#!/bin/bash

cd /Users/clo2/Documents/wdl-sandbox/cromwell-executions/myWorkflow/72dd4409-c10a-418a-82e6-af24a8c19b15/call-myTask/execution
tmpDir=$(mkdir -p "/Users/clo2/Documents/wdl-sandbox/cromwell-executions/myWorkflow/72dd4409-c10a-418a-82e6-af24a8c19b15/call-myTask/tmp.14d0b2d5" && echo "/Users/clo2/Documents/wdl-sandbox/cromwell-executions/myWorkflow/72dd4409-c10a-418a-82e6-af24a8c19b15/call-myTask/tmp.14d0b2d5")

export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /Users/clo2/Documents/wdl-sandbox/cromwell-executions/myWorkflow/72dd4409-c10a-418a-82e6-af24a8c19b15/call-myTask/execution

)
out72dd4409="${tmpDir}/out.$$" err72dd4409="${tmpDir}/err.$$"
mkfifo "$out72dd4409" "$err72dd4409"
trap 'rm "$out72dd4409" "$err72dd4409"' EXIT
touch '/Users/clo2/Documents/wdl-sandbox/cromwell-executions/myWorkflow/72dd4409-c10a-418a-82e6-af24a8c19b15/call-myTask/execution/stdout' '/Users/clo2/Documents/wdl-sandbox/cromwell-executions/myWorkflow/72dd4409-c10a-418a-82e6-af24a8c19b15/call-myTask/execution/stderr'
tee '/Users/clo2/Documents/wdl-sandbox/cromwell-executions/myWorkflow/72dd4409-c10a-418a-82e6-af24a8c19b15/call-myTask/execution/stdout' < "$out72dd4409" &
tee '/Users/clo2/Documents/wdl-sandbox/cromwell-executions/myWorkflow/72dd4409-c10a-418a-82e6-af24a8c19b15/call-myTask/execution/stderr' < "$err72dd4409" >&2 &
(
cd /Users/clo2/Documents/wdl-sandbox/cromwell-executions/myWorkflow/72dd4409-c10a-418a-82e6-af24a8c19b15/call-myTask/execution


echo "hello world"
)  > "$out72dd4409" 2> "$err72dd4409"
echo $? > /Users/clo2/Documents/wdl-sandbox/cromwell-executions/myWorkflow/72dd4409-c10a-418a-82e6-af24a8c19b15/call-myTask/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /Users/clo2/Documents/wdl-sandbox/cromwell-executions/myWorkflow/72dd4409-c10a-418a-82e6-af24a8c19b15/call-myTask/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /Users/clo2/Documents/wdl-sandbox/cromwell-executions/myWorkflow/72dd4409-c10a-418a-82e6-af24a8c19b15/call-myTask/execution
sync


)
mv /Users/clo2/Documents/wdl-sandbox/cromwell-executions/myWorkflow/72dd4409-c10a-418a-82e6-af24a8c19b15/call-myTask/execution/rc.tmp /Users/clo2/Documents/wdl-sandbox/cromwell-executions/myWorkflow/72dd4409-c10a-418a-82e6-af24a8c19b15/call-myTask/execution/rc
