#!/bin/bash

cd /cromwell-executions/myWorkflow/e4b56bd5-44c2-4ff1-950b-4336cab2b406/call-myTask/execution
tmpDir=$(mkdir -p "/cromwell-executions/myWorkflow/e4b56bd5-44c2-4ff1-950b-4336cab2b406/call-myTask/tmp.32b6e4f5" && echo "/cromwell-executions/myWorkflow/e4b56bd5-44c2-4ff1-950b-4336cab2b406/call-myTask/tmp.32b6e4f5")
chmod 777 "$tmpDir"
export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /cromwell-executions/myWorkflow/e4b56bd5-44c2-4ff1-950b-4336cab2b406/call-myTask/execution

)
oute4b56bd5="${tmpDir}/out.$$" erre4b56bd5="${tmpDir}/err.$$"
mkfifo "$oute4b56bd5" "$erre4b56bd5"
trap 'rm "$oute4b56bd5" "$erre4b56bd5"' EXIT
touch '/cromwell-executions/myWorkflow/e4b56bd5-44c2-4ff1-950b-4336cab2b406/call-myTask/execution/stdout' '/cromwell-executions/myWorkflow/e4b56bd5-44c2-4ff1-950b-4336cab2b406/call-myTask/execution/stderr'
tee '/cromwell-executions/myWorkflow/e4b56bd5-44c2-4ff1-950b-4336cab2b406/call-myTask/execution/stdout' < "$oute4b56bd5" &
tee '/cromwell-executions/myWorkflow/e4b56bd5-44c2-4ff1-950b-4336cab2b406/call-myTask/execution/stderr' < "$erre4b56bd5" >&2 &
(
cd /cromwell-executions/myWorkflow/e4b56bd5-44c2-4ff1-950b-4336cab2b406/call-myTask/execution


echo "hello world"
)  > "$oute4b56bd5" 2> "$erre4b56bd5"
echo $? > /cromwell-executions/myWorkflow/e4b56bd5-44c2-4ff1-950b-4336cab2b406/call-myTask/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /cromwell-executions/myWorkflow/e4b56bd5-44c2-4ff1-950b-4336cab2b406/call-myTask/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /cromwell-executions/myWorkflow/e4b56bd5-44c2-4ff1-950b-4336cab2b406/call-myTask/execution
sync


)
mv /cromwell-executions/myWorkflow/e4b56bd5-44c2-4ff1-950b-4336cab2b406/call-myTask/execution/rc.tmp /cromwell-executions/myWorkflow/e4b56bd5-44c2-4ff1-950b-4336cab2b406/call-myTask/execution/rc
