#!/bin/bash

cd /Users/clo2/Documents/wdl-sandbox/linear_chain/cromwell-executions/LinearChainExample/e575df1e-2b58-4368-b8ab-a630f885cac6/call-MarkDuplicates/execution
tmpDir=$(mkdir -p "/Users/clo2/Documents/wdl-sandbox/linear_chain/cromwell-executions/LinearChainExample/e575df1e-2b58-4368-b8ab-a630f885cac6/call-MarkDuplicates/tmp.bbc0ebaa" && echo "/Users/clo2/Documents/wdl-sandbox/linear_chain/cromwell-executions/LinearChainExample/e575df1e-2b58-4368-b8ab-a630f885cac6/call-MarkDuplicates/tmp.bbc0ebaa")

export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /Users/clo2/Documents/wdl-sandbox/linear_chain/cromwell-executions/LinearChainExample/e575df1e-2b58-4368-b8ab-a630f885cac6/call-MarkDuplicates/execution

)
oute575df1e="${tmpDir}/out.$$" erre575df1e="${tmpDir}/err.$$"
mkfifo "$oute575df1e" "$erre575df1e"
trap 'rm "$oute575df1e" "$erre575df1e"' EXIT
touch '/Users/clo2/Documents/wdl-sandbox/linear_chain/cromwell-executions/LinearChainExample/e575df1e-2b58-4368-b8ab-a630f885cac6/call-MarkDuplicates/execution/stdout' '/Users/clo2/Documents/wdl-sandbox/linear_chain/cromwell-executions/LinearChainExample/e575df1e-2b58-4368-b8ab-a630f885cac6/call-MarkDuplicates/execution/stderr'
tee '/Users/clo2/Documents/wdl-sandbox/linear_chain/cromwell-executions/LinearChainExample/e575df1e-2b58-4368-b8ab-a630f885cac6/call-MarkDuplicates/execution/stdout' < "$oute575df1e" &
tee '/Users/clo2/Documents/wdl-sandbox/linear_chain/cromwell-executions/LinearChainExample/e575df1e-2b58-4368-b8ab-a630f885cac6/call-MarkDuplicates/execution/stderr' < "$erre575df1e" >&2 &
(
cd /Users/clo2/Documents/wdl-sandbox/linear_chain/cromwell-executions/LinearChainExample/e575df1e-2b58-4368-b8ab-a630f885cac6/call-MarkDuplicates/execution


cat /Users/clo2/Documents/wdl-sandbox/linear_chain/cromwell-executions/LinearChainExample/e575df1e-2b58-4368-b8ab-a630f885cac6/call-MarkDuplicates/inputs/1253239041/fake.bam > dedupped.bam
)  > "$oute575df1e" 2> "$erre575df1e"
echo $? > /Users/clo2/Documents/wdl-sandbox/linear_chain/cromwell-executions/LinearChainExample/e575df1e-2b58-4368-b8ab-a630f885cac6/call-MarkDuplicates/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /Users/clo2/Documents/wdl-sandbox/linear_chain/cromwell-executions/LinearChainExample/e575df1e-2b58-4368-b8ab-a630f885cac6/call-MarkDuplicates/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /Users/clo2/Documents/wdl-sandbox/linear_chain/cromwell-executions/LinearChainExample/e575df1e-2b58-4368-b8ab-a630f885cac6/call-MarkDuplicates/execution
sync


)
mv /Users/clo2/Documents/wdl-sandbox/linear_chain/cromwell-executions/LinearChainExample/e575df1e-2b58-4368-b8ab-a630f885cac6/call-MarkDuplicates/execution/rc.tmp /Users/clo2/Documents/wdl-sandbox/linear_chain/cromwell-executions/LinearChainExample/e575df1e-2b58-4368-b8ab-a630f885cac6/call-MarkDuplicates/execution/rc
