#!/bin/bash

cd /Users/clo2/Documents/wdl-sandbox/linear_chain/cromwell-executions/LinearChainExample/8c385bf2-e012-4f43-a1bd-95fba4f3c8de/call-MarkDuplicates/execution
tmpDir=$(mkdir -p "/Users/clo2/Documents/wdl-sandbox/linear_chain/cromwell-executions/LinearChainExample/8c385bf2-e012-4f43-a1bd-95fba4f3c8de/call-MarkDuplicates/tmp.9f19f408" && echo "/Users/clo2/Documents/wdl-sandbox/linear_chain/cromwell-executions/LinearChainExample/8c385bf2-e012-4f43-a1bd-95fba4f3c8de/call-MarkDuplicates/tmp.9f19f408")

export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /Users/clo2/Documents/wdl-sandbox/linear_chain/cromwell-executions/LinearChainExample/8c385bf2-e012-4f43-a1bd-95fba4f3c8de/call-MarkDuplicates/execution

)
out8c385bf2="${tmpDir}/out.$$" err8c385bf2="${tmpDir}/err.$$"
mkfifo "$out8c385bf2" "$err8c385bf2"
trap 'rm "$out8c385bf2" "$err8c385bf2"' EXIT
touch '/Users/clo2/Documents/wdl-sandbox/linear_chain/cromwell-executions/LinearChainExample/8c385bf2-e012-4f43-a1bd-95fba4f3c8de/call-MarkDuplicates/execution/stdout' '/Users/clo2/Documents/wdl-sandbox/linear_chain/cromwell-executions/LinearChainExample/8c385bf2-e012-4f43-a1bd-95fba4f3c8de/call-MarkDuplicates/execution/stderr'
tee '/Users/clo2/Documents/wdl-sandbox/linear_chain/cromwell-executions/LinearChainExample/8c385bf2-e012-4f43-a1bd-95fba4f3c8de/call-MarkDuplicates/execution/stdout' < "$out8c385bf2" &
tee '/Users/clo2/Documents/wdl-sandbox/linear_chain/cromwell-executions/LinearChainExample/8c385bf2-e012-4f43-a1bd-95fba4f3c8de/call-MarkDuplicates/execution/stderr' < "$err8c385bf2" >&2 &
(
cd /Users/clo2/Documents/wdl-sandbox/linear_chain/cromwell-executions/LinearChainExample/8c385bf2-e012-4f43-a1bd-95fba4f3c8de/call-MarkDuplicates/execution


cat /Users/clo2/Documents/wdl-sandbox/linear_chain/cromwell-executions/LinearChainExample/8c385bf2-e012-4f43-a1bd-95fba4f3c8de/call-MarkDuplicates/inputs/1253239041/fake.bam > 123_id.markDuplicates.bam
)  > "$out8c385bf2" 2> "$err8c385bf2"
echo $? > /Users/clo2/Documents/wdl-sandbox/linear_chain/cromwell-executions/LinearChainExample/8c385bf2-e012-4f43-a1bd-95fba4f3c8de/call-MarkDuplicates/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /Users/clo2/Documents/wdl-sandbox/linear_chain/cromwell-executions/LinearChainExample/8c385bf2-e012-4f43-a1bd-95fba4f3c8de/call-MarkDuplicates/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /Users/clo2/Documents/wdl-sandbox/linear_chain/cromwell-executions/LinearChainExample/8c385bf2-e012-4f43-a1bd-95fba4f3c8de/call-MarkDuplicates/execution
sync


)
mv /Users/clo2/Documents/wdl-sandbox/linear_chain/cromwell-executions/LinearChainExample/8c385bf2-e012-4f43-a1bd-95fba4f3c8de/call-MarkDuplicates/execution/rc.tmp /Users/clo2/Documents/wdl-sandbox/linear_chain/cromwell-executions/LinearChainExample/8c385bf2-e012-4f43-a1bd-95fba4f3c8de/call-MarkDuplicates/execution/rc
