#!/bin/bash

cd /Users/clo2/Documents/wdl-sandbox/linear_chain/cromwell-executions/LinearChainExample/e575df1e-2b58-4368-b8ab-a630f885cac6/call-HaplotypeCaller/execution
tmpDir=$(mkdir -p "/Users/clo2/Documents/wdl-sandbox/linear_chain/cromwell-executions/LinearChainExample/e575df1e-2b58-4368-b8ab-a630f885cac6/call-HaplotypeCaller/tmp.12f84bf8" && echo "/Users/clo2/Documents/wdl-sandbox/linear_chain/cromwell-executions/LinearChainExample/e575df1e-2b58-4368-b8ab-a630f885cac6/call-HaplotypeCaller/tmp.12f84bf8")

export _JAVA_OPTIONS=-Djava.io.tmpdir="$tmpDir"
export TMPDIR="$tmpDir"
export HOME="$HOME"
(
cd /Users/clo2/Documents/wdl-sandbox/linear_chain/cromwell-executions/LinearChainExample/e575df1e-2b58-4368-b8ab-a630f885cac6/call-HaplotypeCaller/execution

)
oute575df1e="${tmpDir}/out.$$" erre575df1e="${tmpDir}/err.$$"
mkfifo "$oute575df1e" "$erre575df1e"
trap 'rm "$oute575df1e" "$erre575df1e"' EXIT
touch '/Users/clo2/Documents/wdl-sandbox/linear_chain/cromwell-executions/LinearChainExample/e575df1e-2b58-4368-b8ab-a630f885cac6/call-HaplotypeCaller/execution/stdout' '/Users/clo2/Documents/wdl-sandbox/linear_chain/cromwell-executions/LinearChainExample/e575df1e-2b58-4368-b8ab-a630f885cac6/call-HaplotypeCaller/execution/stderr'
tee '/Users/clo2/Documents/wdl-sandbox/linear_chain/cromwell-executions/LinearChainExample/e575df1e-2b58-4368-b8ab-a630f885cac6/call-HaplotypeCaller/execution/stdout' < "$oute575df1e" &
tee '/Users/clo2/Documents/wdl-sandbox/linear_chain/cromwell-executions/LinearChainExample/e575df1e-2b58-4368-b8ab-a630f885cac6/call-HaplotypeCaller/execution/stderr' < "$erre575df1e" >&2 &
(
cd /Users/clo2/Documents/wdl-sandbox/linear_chain/cromwell-executions/LinearChainExample/e575df1e-2b58-4368-b8ab-a630f885cac6/call-HaplotypeCaller/execution


cat /Users/clo2/Documents/wdl-sandbox/linear_chain/cromwell-executions/LinearChainExample/e575df1e-2b58-4368-b8ab-a630f885cac6/call-HaplotypeCaller/inputs/-1874866692/dedupped.bam > rawVariants.vcf
)  > "$oute575df1e" 2> "$erre575df1e"
echo $? > /Users/clo2/Documents/wdl-sandbox/linear_chain/cromwell-executions/LinearChainExample/e575df1e-2b58-4368-b8ab-a630f885cac6/call-HaplotypeCaller/execution/rc.tmp
(
# add a .file in every empty directory to facilitate directory delocalization on the cloud
cd /Users/clo2/Documents/wdl-sandbox/linear_chain/cromwell-executions/LinearChainExample/e575df1e-2b58-4368-b8ab-a630f885cac6/call-HaplotypeCaller/execution
find . -type d -exec sh -c '[ -z "$(ls -A '"'"'{}'"'"')" ] && touch '"'"'{}'"'"'/.file' \;
)
(
cd /Users/clo2/Documents/wdl-sandbox/linear_chain/cromwell-executions/LinearChainExample/e575df1e-2b58-4368-b8ab-a630f885cac6/call-HaplotypeCaller/execution
sync


)
mv /Users/clo2/Documents/wdl-sandbox/linear_chain/cromwell-executions/LinearChainExample/e575df1e-2b58-4368-b8ab-a630f885cac6/call-HaplotypeCaller/execution/rc.tmp /Users/clo2/Documents/wdl-sandbox/linear_chain/cromwell-executions/LinearChainExample/e575df1e-2b58-4368-b8ab-a630f885cac6/call-HaplotypeCaller/execution/rc
